name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet

      - name: Build APK
        run: flet build apk --verbose

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/apk/app-release.apk
            build/apk/app-release.apk.sha1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
