name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install supabase==2.10.0
          # pip install flet
          # pip install supabase
          
        

      # 自动创建 tag（仅 workflow_dispatch 手动触发时）
      - name: Create tag if not exists
        if: github.event_name == 'workflow_dispatch'
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build APK
        run: flet build apk --verbose

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/apk/app-release.apk
            build/apk/app-release.apk.sha1
          tag_name: ${{ github.ref_name || env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
