name: Build and Release APK

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install supabase==2.10.0
          # pip install flet
          # pip install supabase
          
        

      # 自动创建 tag（仅 workflow_dispatch 手动触发时）
      - name: Create tag if not exists
        if: github.event_name == 'workflow_dispatch'
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # 自动生成带时间的 Release 标题
      - name: Set release title
        run: |
          echo "RELEASE_TITLE=Release $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Build APK
        run: flet build apk -o output/apk --verbose
        continue-on-error: true

      - name: Build window executable
        run: flet build windows -o output/windows --verbose
        continue-on-error: true

      - name: Build macOS executable
        run: flet build macos -o output/macos --verbose
        continue-on-error: true

      - name: Build Linux executable
        run: flet build linux -o output/linux --verbose
        continue-on-error: true

      - name: Build web
        run: flet build web -o output/web --verbose
        continue-on-error: true

      # - name: Copy web build to repo root
      #   run: |
      #     cp -r output/web/* .
      #   continue-on-error: true

      - name: Commit and push web build to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: update web build [skip ci]" || echo "Nothing to commit"
          git push
        continue-on-error: true

      - name: Zip web build
        run: |
          cd output/web
          zip -r ../web.zip .
        continue-on-error: true

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/apk/*
            output/windows/*
            output/macos/*
            output/linux/*
            output/web.zip
          tag_name: ${{ github.ref_name || env.TAG_NAME }}
          name: ${{ env.RELEASE_TITLE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
